#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rake/clean'
require 'rake/testtask'
require 'rdoc/task'
require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'swagger/blocks'
require 'json'
require 'fileutils'

# NPM Utilities and Tasks
namespace :npm do
  # Make methods public within the namespace
  public

  # Check if npm is installed
  def npm_installed?
    system('npm --version > /dev/null 2>&1')
  end

  # Ensure npm is installed
  def ensure_npm_installed
    return if npm_installed?

    abort "Error: npm is not installed. Please install Node.js and npm first."
  end

  # Create package.json if it doesn't exist
  def ensure_package_json(dir, options = {})
    package_path = File.join(dir, 'package.json')
    return if File.exist?(package_path)

    puts "Creating package.json in #{dir}..."

    # Default package.json content
    package_content = {
      name: options[:name] || File.basename(dir),
      version: options[:version] || '1.0.0',
      description: options[:description] || 'Generated by Rake',
      scripts: options[:scripts] || {},
      dependencies: options[:dependencies] || {},
      devDependencies: options[:devDependencies] || {}
    }

    # Create directory if it doesn't exist
    FileUtils.mkdir_p(dir) unless Dir.exist?(dir)

    # Write package.json
    File.write(package_path, JSON.pretty_generate(package_content))
    puts "Created package.json in #{dir}"
  end

  # Install npm dependencies if needed
  def ensure_dependencies(dir)
    return unless Dir.exist?(dir)

    # Check if node_modules exists
    return if Dir.exist?(File.join(dir, 'node_modules'))

    puts "Installing npm dependencies in #{dir}..."
    Dir.chdir(dir) do
      system('npm install --quiet --no-progress') or abort("Failed to install npm dependencies in #{dir}")
    end
    puts "Dependencies installed in #{dir}"
  end

  # Run npm script with proper error handling
  def run_npm_script(dir, script, args = '')
    ensure_npm_installed
    ensure_package_json(dir)
    ensure_dependencies(dir)

    puts "Running npm script '#{script}' in #{dir}..."
    Dir.chdir(dir) do
      system("npm run #{script} #{args}") or abort("Failed to run '#{script}' in #{dir}")
    end
  end

  desc 'Initialize package.json in the docs directory'
  task :init_docs do
    # Skip if package.json already exists (likely created by Docusaurus init)
    unless File.exist?('docs/package.json')
      docusaurus_deps = {
        '@docusaurus/core' => '^2.4.1',
        '@docusaurus/preset-classic' => '^2.4.1',
        'react' => '^17.0.2',
        'react-dom' => '^17.0.2'
      }

      docusaurus_scripts = {
        'start' => 'docusaurus start',
        'build' => 'docusaurus build',
        'serve' => 'docusaurus serve'
      }

      ensure_package_json('docs', {
                            name: 'docs',
                            description: 'Documentation site',
                            scripts: docusaurus_scripts,
                            dependencies: docusaurus_deps
                          })
    end
  end

  desc 'Initialize package.json in the project root for tools'
  task :init_root do
    tools_deps = {
      '@redocly/cli' => '^1.0.0'
    }

    tools_scripts = {
      'lint-openapi' => 'redocly lint'
    }

    ensure_package_json('.', {
                          name: ENV['GEM_NAME'] || 'promptly',
                          description: 'Project tools',
                          scripts: tools_scripts,
                          devDependencies: tools_deps
                        })
  end

  desc 'Install all npm dependencies'
  task install: %i[init_docs init_root] do
    ensure_dependencies('.')
    ensure_dependencies('docs')
    puts "All npm dependencies installed"
  end

  desc 'Run an npm script in a specified directory'
  task :run, [:dir, :script, :args] do |_t, args|
    dir = args[:dir] || '.'
    script = args[:script] || 'start'
    script_args = args[:args] || ''
    run_npm_script(dir, script, script_args)
  end

  desc 'Clean all npm dependencies'
  task :clean do
    rm_rf ['node_modules', 'docs/node_modules']
    puts "Cleaned npm dependencies"
  end
end

namespace :docs do
  # RDoc Configuration
  RDoc::Task.new(:rdoc) do |t|
    t.main = "README.md"
    t.rdoc_files.include("README.md", "lib/**/*.rb", "guides/Usage.md")
    t.options << "--format=markdown"
    t.options << "--markup=markdown"
    t.rdoc_dir = "doc"
    t.title = "#{ENV['GEM_NAME'] || 'RubyGem'} Documentation"
  end

  # Swagger-blocks Configuration
  namespace :openapi do
    desc 'Generate OpenAPI specification'
    task :generate do
      require "swagger_definitions" # Point to your swagger-blocks file

      swagger_data = Swagger::Blocks.build_root_json([SwaggerDefinitions])
      mkdir_p "public/api_docs/v1"
      File.write("public/api_docs/v1/swagger.json", JSON.pretty_generate(swagger_data))
    end

    desc 'Validate OpenAPI specs'
    task validate: :generate do
      # Ensure npm and dependencies are available
      Rake::Task['npm:init_root'].invoke

      # Use npm utility function to run the validation
      sh "npx @redocly/cli lint public/api_docs/v1/swagger.json" do |ok|
        abort("OpenAPI validation failed") unless ok
      end
    end
  end

  # Docusaurus Integration
  desc 'Initialize Docusaurus site if it does not exist'
  task :init_docusaurus do
    # Check if Docusaurus config exists
    unless File.exist?('docs/docusaurus.config.js')
      puts "Docusaurus site not initialized. Creating a new site..."

      # Create a temporary directory for initialization
      temp_dir = 'docs_temp'
      # mkdir_p temp_dir

      # Initialize a new Docusaurus site in the temporary directory
      sh "npx @docusaurus/init@latest init #{temp_dir} classic" do |ok|
        unless ok
          rm_rf temp_dir
          abort("Failed to initialize Docusaurus site")
        end
      end

      # Move necessary files to the docs directory
      mkdir_p 'docs'

      # Copy configuration files
      cp "#{temp_dir}/docusaurus.config.js", 'docs/'
      cp "#{temp_dir}/babel.config.js", 'docs/'
      cp "#{temp_dir}/package.json", 'docs/'
      cp "#{temp_dir}/sidebars.js", 'docs/'

      # Create necessary directories
      mkdir_p 'docs/src/pages'
      mkdir_p 'docs/src/components'
      mkdir_p 'docs/src/css'
      mkdir_p 'docs/static/img'
      mkdir_p 'docs/docs'
      mkdir_p 'docs/blog'

      # Copy essential files
      cp_r "#{temp_dir}/src/.", 'docs/src/', remove_destination: true
      cp_r "#{temp_dir}/static/.", 'docs/static/', remove_destination: true
      cp_r "#{temp_dir}/docs/.", 'docs/docs/', remove_destination: true
      cp_r "#{temp_dir}/blog/.", 'docs/blog/', remove_destination: true

      # Clean up temporary directory
      rm_rf temp_dir

      puts "Docusaurus site initialized successfully"

      # Update docusaurus.config.js to use our project name
      docusaurus_config = File.read('docs/docusaurus.config.js')
      docusaurus_config.gsub!('My Site', "#{ENV['GEM_NAME'] || 'Promptly'} Documentation")
      docusaurus_config.gsub!('my-site', "#{ENV['GEM_NAME']&.downcase || 'promptly'}-docs")
      File.write('docs/docusaurus.config.js', docusaurus_config)
    end
  end

  desc 'Build documentation site'
  task docusaurus: %i[rdoc openapi:validate init_docusaurus] do
    # Ensure directories exist
    mkdir_p "docs/docs/rdoc"
    mkdir_p "docs/static/api_docs"

    # Copy documentation files
    cp_r "doc/.", "docs/docs/rdoc", remove_destination: true
    cp_r "public/api_docs", "docs/static/api_docs", remove_destination: true

    # Install dependencies
    run_npm_script('docs', 'build')
  end

  desc 'Serve documentation locally'
  task serve: [:init_docusaurus] do
    # Use the global helper method to run the start script
    run_npm_script('docs', 'start')
  end

  desc 'Clean generated artifacts'
  task :clean do
    rm_rf ["doc", "public/api_docs", "docs/build", "docs/node_modules"]
  end

  desc 'Clean all Docusaurus files (for fresh start)'
  task :clean_all do
    Rake::Task['docs:clean'].invoke
    rm_rf ["docs/docusaurus.config.js", "docs/babel.config.js", "docs/sidebars.js",
           "docs/src", "docs/static", "docs/blog", "docs/docs"]
  end
end

# Define helper method for npm script execution
def run_npm_script(dir, script, args = '')
  # Check if npm is installed
  abort "Error: npm is not installed. Please install Node.js and npm first." unless system('npm --version > /dev/null 2>&1')

  # Ensure package.json exists
  package_path = File.join(dir, 'package.json')
  unless File.exist?(package_path)
    # Initialize appropriate package.json based on directory
    if dir == 'docs'
      Rake::Task['npm:init_docs'].invoke
    else
      Rake::Task['npm:init_root'].invoke
    end
  end

  # Ensure dependencies are installed
  node_modules_path = File.join(dir, 'node_modules')
  if !Dir.exist?(node_modules_path) && Dir.exist?(dir)
    puts "Installing npm dependencies in #{dir}..."
    Dir.chdir(dir) do
      system('npm install --quiet --no-progress') or abort("Failed to install npm dependencies in #{dir}")
    end
    puts "Dependencies installed in #{dir}"
  end

  # Run the npm script
  puts "Running npm script '#{script}' in #{dir}..."
  Dir.chdir(dir) do
    system("npm run #{script} #{args}") or abort("Failed to run '#{script}' in #{dir}")
  end
end

# Main documentation tasks
task docs: ['docs:rdoc', 'docs:openapi:validate', 'docs:docusaurus']
task clobber: ['docs:clean_all', 'npm:clean']

# Add npm installation as a prerequisite for the docs task
task docs: ['npm:install']

# Testing task
RSpec::Core::RakeTask.new(:spec)

# Default task
task default: :spec
