#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gli'
require 'tty-config'
require 'fileutils'

# --- Configuration Loading ---
$config = TTY::Config.new
config_dir = File.join(Dir.home, '.config', 'promptly')
config_file = File.join(config_dir, 'config.yml')
prompts_dir = File.join(config_dir, 'prompts')

# Create directories if they don't exist
FileUtils.mkdir_p(config_dir)
FileUtils.mkdir_p(prompts_dir)

# Set default values
$config.set(:prompts_directory, value: prompts_dir)
$config.set(:default_editor, value: ENV.fetch('EDITOR', nil)) # Use ENV['EDITOR'] or nil

# Read config file if it exists, merging with defaults
$config.append_path config_dir
$config.read(config_file, format: :yaml) if File.exist?(config_file)

# Ensure essential keys exist even if file didn't
$config.set(:prompts_directory, value: prompts_dir)
# --- End Configuration Loading ---

begin
  require 'promptly'
rescue LoadError
  warn 'In development, you need to use `bundle exec bin/promptly` to run your app'
  warn 'At install-time, RubyGems will make sure lib, etc. are in the load path'
  exit 64
end

Promptly::CLI.start(ARGV)
